### ISSUE TITLE
错误代码？请问是什么原因？

### ISSUE THREAD

**Issue by angel126** [cdhigh/KindleEar#158]
E:\Downloads\Tools\Goagent\Kindle\kindleear_uploader>
it

E:\Downloads\Tools\Goagent\Kindle\kindleear_uploader>
dle

E:\Downloads\Tools\Goagent\Kindle\kindleear_uploader>
le-worker.yaml goto kindle-dir

E:\Downloads\Tools\Goagent\Kindle\kindleear_uploader>
_sdk_update_check update kindleear\app.yaml kindleear
10:00 PM Host: appengine.google.com
10:00 PM Application: henry-rss; version: 1
10:00 PM
Starting update of app: henry-rss, version: 1
10:00 PM Getting current resource limits.
2015-01-11 22:08:34,086 ERROR appcfg.py:2323 An error
': <urlopen error [Errno 10060] >. Aborting.
Traceback (most recent call last):
  File "appcfg.py", line 170, in <module>
    run_file(__file__, globals())
  File "appcfg.py", line 166, in run_file
    execfile(script_path, globals_)
  File "E:\Downloads\Tools\Goagent\Kindle\kindleear_u
ols\appcfg.py", line 5214, in <module>
    main(sys.argv)
  File "E:\Downloads\Tools\Goagent\Kindle\kindleear_u
ols\appcfg.py", line 5205, in main
    result = AppCfgApp(argv).Run()
  File "E:\Downloads\Tools\Goagent\Kindle\kindleear_u
ols\appcfg.py", line 2885, in Run
    self.action(self)
  File "E:\Downloads\Tools\Goagent\Kindle\kindleear_u
ols\appcfg.py", line 4884, in __call__
    return method()
  File "E:\Downloads\Tools\Goagent\Kindle\kindleear_u
ols\appcfg.py", line 3649, in Update
    self.UpdateUsingSpecificFiles()
  File "E:\Downloads\Tools\Goagent\Kindle\kindleear_u
ols\appcfg.py", line 3641, in UpdateUsingSpecificFile
    self.UpdateVersion(rpcserver, self.basepath, modu
  File "E:\Downloads\Tools\Goagent\Kindle\kindleear_u
ols\appcfg.py", line 3617, in UpdateVersion
    return appversion.DoUpload(paths, openfunc)
  File "E:\Downloads\Tools\Goagent\Kindle\kindleear_u
ols\appcfg.py", line 2313, in DoUpload
    self.error_fh)
  File "E:\Downloads\Tools\Goagent\Kindle\kindleear_u
ols\appcfg.py", line 466, in GetResourceLimits
    resource_limits.update(_GetRemoteResourceLimits(l
  File "E:\Downloads\Tools\Goagent\Kindle\kindleear_u
ols\appcfg.py", line 436, in _GetRemoteResourceLimits
    yaml_data = logging_context.Send('/api/appversion
  File "E:\Downloads\Tools\Goagent\Kindle\kindleear_u
ols\appcfg.py", line 1683, in Send
    result = self.rpcserver.Send(url, payload=payload
  File "E:\Downloads\Tools\Goagent\Kindle\kindleear_u
ols\appengine_rpc.py", line 409, in Send
    f = self.opener.open(req)
  File "E:\Downloads\Tools\Goagent\Kindle\kindleear_u
ne 404, in open
    response = self._open(req, data)
  File "E:\Downloads\Tools\Goagent\Kindle\kindleear_u
ne 422, in _open
    '_open', req)
  File "E:\Downloads\Tools\Goagent\Kindle\kindleear_u
ne 382, in _call_chain
    result = func(*args)
  File "E:\Downloads\Tools\Goagent\Kindle\kindleear_u
ne 1222, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "E:\Downloads\Tools\Goagent\Kindle\kindleear_u
ncy_urllib\__init__.py", line 387, in do_open
    raise url_error
urllib2.URLError: <urlopen error [Errno 10060] >

**Comment by cdhigh** [comment]
网络出错，或者本地python环境有冲突吧，不知解决了没有

**Comment by angel126** [comment]
这个问题解决了，上传问题。。
