### ISSUE TITLE
投递失败

### ISSUE THREAD

**Issue by fushcpc** [cdhigh/KindleEar#162]
自动和手动投递都没有成功，显示“internal server error"，APP的后台log为：
2015-01-27 06:26:55.343 /deliver?u=admin 500 442ms 0kb Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.91 Safari/537.36 module=default version=1
23.238.230.63 - - [26/Jan/2015:14:26:55 -0800] "GET /deliver?u=admin HTTP/1.1" 500 155 "http://fushcpckindle.appspot.com/setting" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.91 Safari/537.36" "fushcpckindle.appspot.com" ms=443 cpu_ms=57 cpm_usd=0.000017 app_engine_release=1.9.17 instance=00c61b117cc7a79ffc83fdb8324c2fefa098b3c1
E 2015-01-27 06:26:55.341
Traceback (most recent call last):
E 2015-01-27 06:26:55.341
  File "/base/data/home/apps/s~fushcpckindle/1.381798600196292722/lib/web/application.py", line 239, in process
E 2015-01-27 06:26:55.341
    return self.handle()
E 2015-01-27 06:26:55.341
  File "/base/data/home/apps/s~fushcpckindle/1.381798600196292722/lib/web/application.py", line 230, in handle
E 2015-01-27 06:26:55.341
    return self._delegate(fn, self.fvars, args)
E 2015-01-27 06:26:55.341
  File "/base/data/home/apps/s~fushcpckindle/1.381798600196292722/lib/web/application.py", line 420, in _delegate
E 2015-01-27 06:26:55.341
    return handle_class(cls)
E 2015-01-27 06:26:55.341
  File "/base/data/home/apps/s~fushcpckindle/1.381798600196292722/lib/web/application.py", line 396, in handle_class
E 2015-01-27 06:26:55.341
    return tocall(*args)
E 2015-01-27 06:26:55.341
  File "/base/data/home/apps/s~fushcpckindle/1.381798600196292722/apps/View/Deliver.py", line 56, in GET
E 2015-01-27 06:26:55.341
    self.queueit(user, book.key().id(), book.separate)
E 2015-01-27 06:26:55.341
  File "/base/data/home/apps/s~fushcpckindle/1.381798600196292722/apps/View/Deliver.py", line 31, in queueit
E 2015-01-27 06:26:55.341
    params=param,target="worker")
E 2015-01-27 06:26:55.341
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/taskqueue/taskqueue.py", line 2286, in add
E 2015-01-27 06:26:55.341
    queue_name=queue_name, transactional=transactional)
E 2015-01-27 06:26:55.341
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/taskqueue/taskqueue.py", line 1134, in add
E 2015-01-27 06:26:55.341
    return self.add_async(queue_name, transactional).get_result()
E 2015-01-27 06:26:55.341
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/apiproxy_stub_map.py", line 613, in get_result
E 2015-01-27 06:26:55.341
    return self.__get_result_hook(self)
E 2015-01-27 06:26:55.341
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/taskqueue/taskqueue.py", line 1960, in ResultHook
E 2015-01-27 06:26:55.341
    raise exception
E 2015-01-27 06:26:55.341
UnknownQueueError

**Comment by fushcpc** [comment]
![1](https://cloud.githubusercontent.com/assets/3312370/5909780/8b24ed4c-a5ee-11e4-8ecb-8cae5008578e.png)
![2](https://cloud.githubusercontent.com/assets/3312370/5909779/8b249950-a5ee-11e4-8dbd-89bb9d3dee0b.png)

**Comment by fuyufjh** [comment]
I have encountered the same problem... Waiting for the author now

**Comment by cdhigh** [comment]
#122
