### ISSUE TITLE
运行uploader.bat时出现错误，应如何解决

### ISSUE THREAD

**Issue by hsda** [cdhigh/KindleEar#182]
D:\kindleear_uploader>set PYTHONPATH=D:\kindleear_uploader\DLLs;D:\kindleear_uploader\libs;D:\kindleear_uploader\lib

D:\kindleear_uploader>python.exe helper.py

KindleEar uploader v1.2 (2014-04-28) by cdhigh

Traceback (most recent call last):
  File "helper.py", line 173, in <module>
    ret = Main()
  File "helper.py", line 50, in Main
    slcfg = fcfg.read().split('\n')
  File "D:\kindleear_uploader\lib\codecs.py", line 671, in read
    return self.reader.read(size)
  File "D:\kindleear_uploader\lib\codecs.py", line 477, in read
    newchars, decodedbytes = self.decode(data, self.errors)
UnicodeDecodeError: 'utf8' codec can't decode bytes in position 231-232: invalid
 continuation byte

D:\kindleear_uploader>if errorlevel 1 pause && exit

**Comment by hsda** [comment]
我明白了，是我自己搞错了，我先把文件都改了之后再打开uploader.bat
