### ISSUE TITLE
urlerroe

### ISSUE THREAD

**Issue by lionel0822** [cdhigh/KindleEar#183]
upload.bat  出现url open error
2015-03-29 00:04:49,484 ERROR appcfg.py:2323 An error occurred processing file '
': <urlopen error [Errno 10060] >. Aborting.
Traceback (most recent call last):
  File "appcfg.py", line 170, in <module>
    run_file(__file__, globals())
  File "appcfg.py", line 166, in run_file
    execfile(script_path, globals_)
  File "D:\Program Files (x86)\kindleear_uploader\google\appengine\tools\appcfg.
py", line 5214, in <module>
    main(sys.argv)
  File "D:\Program Files (x86)\kindleear_uploader\google\appengine\tools\appcfg.
py", line 5205, in main
    result = AppCfgApp(argv).Run()
  File "D:\Program Files (x86)\kindleear_uploader\google\appengine\tools\appcfg.
py", line 2885, in Run
    self.action(self)
  File "D:\Program Files (x86)\kindleear_uploader\google\appengine\tools\appcfg.
py", line 4884, in __call__
    return method()
  File "D:\Program Files (x86)\kindleear_uploader\google\appengine\tools\appcfg.
py", line 3649, in Update
    self.UpdateUsingSpecificFiles()
  File "D:\Program Files (x86)\kindleear_uploader\google\appengine\tools\appcfg.
py", line 3641, in UpdateUsingSpecificFiles
    self.UpdateVersion(rpcserver, self.basepath, module_yaml, file_name)
  File "D:\Program Files (x86)\kindleear_uploader\google\appengine\tools\appcfg.
py", line 3617, in UpdateVersion
    return appversion.DoUpload(paths, openfunc)
  File "D:\Program Files (x86)\kindleear_uploader\google\appengine\tools\appcfg.
py", line 2313, in DoUpload
    self.error_fh)
  File "D:\Program Files (x86)\kindleear_uploader\google\appengine\tools\appcfg.
py", line 466, in GetResourceLimits
    resource_limits.update(_GetRemoteResourceLimits(logging_context))
  File "D:\Program Files (x86)\kindleear_uploader\google\appengine\tools\appcfg.
py", line 436, in _GetRemoteResourceLimits
    yaml_data = logging_context.Send('/api/appversion/getresourcelimits')
  File "D:\Program Files (x86)\kindleear_uploader\google\appengine\tools\appcfg.
py", line 1683, in Send
    result = self.rpcserver.Send(url, payload=payload, **kwargs)
  File "D:\Program Files (x86)\kindleear_uploader\google\appengine\tools\appengi
ne_rpc.py", line 423, in Send
    self._Authenticate()
  File "D:\Program Files (x86)\kindleear_uploader\google\appengine\tools\appengi
ne_rpc.py", line 564, in _Authenticate
    super(HttpRpcServer, self)._Authenticate()
  File "D:\Program Files (x86)\kindleear_uploader\google\appengine\tools\appengi
ne_rpc.py", line 314, in _Authenticate
    auth_token = self._GetAuthToken(credentials[0], credentials[1])
  File "D:\Program Files (x86)\kindleear_uploader\google\appengine\tools\appengi
ne_rpc.py", line 253, in _GetAuthToken
    response = self.opener.open(req)
  File "D:\Program Files (x86)\kindleear_uploader\lib\urllib2.py", line 404, in
open
    response = self._open(req, data)
  File "D:\Program Files (x86)\kindleear_uploader\lib\urllib2.py", line 422, in
_open
    '_open', req)
  File "D:\Program Files (x86)\kindleear_uploader\lib\urllib2.py", line 382, in
_call_chain
    result = func(*args)
  File "D:\Program Files (x86)\kindleear_uploader\lib\urllib2.py", line 1222, in
 https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "D:\Program Files (x86)\kindleear_uploader\lib\fancy_urllib\fancy_urllib\
__init__.py", line 387, in do_open
    raise url_error
urllib2.URLError: <urlopen error [Errno 10060] >

**Comment by cdhigh** [comment]
被墙了吧，翻了吗

**Comment by lionel0822** [comment]
谢谢你的回复  我昨天翻墙后   ok啦 
谢谢分享这么好的东西。。。。
