### ISSUE TITLE
I got a problem?

### ISSUE THREAD

**Issue by jan167** [cdhigh/KindleEar#184]
when I uploading the project ,it tipped  like these:
Correct? (y/n) : y

F:\kindleear_uploader>if errorlevel 1 pause && exit

F:\kindleear_uploader>if exist kindleear goto kindle

F:\kindleear_uploader>if not exist kindleear\module-worker.yaml goto kindle-dir

F:\kindleear_uploader>python.exe appcfg.py --skip_sdk_update_check update kindle
ear\app.yaml kindleear\module-worker.yaml
10:43 AM Host: appengine.google.com
10:43 AM Application: syaokindle; version: 1
10:43 AM
Starting update of app: syaokindle, version: 1
10:43 AM Getting current resource limits.
2015-04-07 10:51:18,589 ERROR appcfg.py:2323 An error occurred processing file '
': <urlopen error [Errno 10060] >. Aborting.
Traceback (most recent call last):
  File "appcfg.py", line 170, in <module>
    run_file(__file__, globals())
  File "appcfg.py", line 166, in run_file
    execfile(script_path, globals_)
  File "F:\kindleear_uploader\google\appengine\tools\appcfg.py", line 5214, in <
module>
    main(sys.argv)
  File "F:\kindleear_uploader\google\appengine\tools\appcfg.py", line 5205, in m
ain
    result = AppCfgApp(argv).Run()
  File "F:\kindleear_uploader\google\appengine\tools\appcfg.py", line 2885, in R
un
    self.action(self)
  File "F:\kindleear_uploader\google\appengine\tools\appcfg.py", line 4884, in _
_call__
    return method()
  File "F:\kindleear_uploader\google\appengine\tools\appcfg.py", line 3649, in U
pdate
    self.UpdateUsingSpecificFiles()
  File "F:\kindleear_uploader\google\appengine\tools\appcfg.py", line 3641, in U
pdateUsingSpecificFiles
    self.UpdateVersion(rpcserver, self.basepath, module_yaml, file_name)
  File "F:\kindleear_uploader\google\appengine\tools\appcfg.py", line 3617, in U
pdateVersion
    return appversion.DoUpload(paths, openfunc)
  File "F:\kindleear_uploader\google\appengine\tools\appcfg.py", line 2313, in D
oUpload
    self.error_fh)
  File "F:\kindleear_uploader\google\appengine\tools\appcfg.py", line 466, in Ge
tResourceLimits
    resource_limits.update(_GetRemoteResourceLimits(logging_context))
  File "F:\kindleear_uploader\google\appengine\tools\appcfg.py", line 436, in _G
etRemoteResourceLimits
    yaml_data = logging_context.Send('/api/appversion/getresourcelimits')
  File "F:\kindleear_uploader\google\appengine\tools\appcfg.py", line 1683, in S
end
    result = self.rpcserver.Send(url, payload=payload, **kwargs)
  File "F:\kindleear_uploader\google\appengine\tools\appengine_rpc.py", line 409
, in Send
    f = self.opener.open(req)
  File "F:\kindleear_uploader\lib\urllib2.py", line 404, in open
    response = self._open(req, data)
  File "F:\kindleear_uploader\lib\urllib2.py", line 422, in _open
    '_open', req)
  File "F:\kindleear_uploader\lib\urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "F:\kindleear_uploader\lib\urllib2.py", line 1222, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "F:\kindleear_uploader\lib\fancy_urllib\fancy_urllib\__init__.py", line 3
87, in do_open
    raise url_error
urllib2.URLError: <urlopen error [Errno 10060] >

F:\kindleear_uploader>python.exe appcfg.py --skip_sdk_update_check update kindle
ear
10:51 AM Application: syaokindle; version: 1
10:51 AM Host: appengine.google.com
10:51 AM
Starting update of app: syaokindle, version: 1
10:51 AM Getting current resource limits.

**Comment by jan167** [comment]
I have done. it was about China firewall.
