### ISSUE TITLE
安装后使用立即投递出现内部错误

### ISSUE THREAD

**Issue by wtbhk** [cdhigh/KindleEar#196]
安装好之后随便订阅了一个知乎日报，点现在投递报错：

```
2015-05-13 07:51:51.358 /deliver?u=admin 500 313ms 0kb Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.69 Safari/537.36 module=default version=1
116.251.209.131 - - [13/May/2015:07:51:51 -0700] "GET /deliver?u=admin HTTP/1.1" 500 155 "http://kanikanikindle.appspot.com/setting" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.69 Safari/537.36" "kanikanikindle.appspot.com" ms=314 cpu_ms=51 cpm_usd=0.000017 app_engine_release=1.9.20 instance=00c61b117c5bfdf634f48d1f37763b9710af3f
E 2015-05-13 07:51:51.352
Traceback (most recent call last):
E 2015-05-13 07:51:51.352
  File "/base/data/home/apps/s~kanikanikindle/1.384273015607921030/lib/web/application.py", line 239, in process
E 2015-05-13 07:51:51.352
    return self.handle()
E 2015-05-13 07:51:51.353
  File "/base/data/home/apps/s~kanikanikindle/1.384273015607921030/lib/web/application.py", line 230, in handle
E 2015-05-13 07:51:51.353
    return self._delegate(fn, self.fvars, args)
E 2015-05-13 07:51:51.353
  File "/base/data/home/apps/s~kanikanikindle/1.384273015607921030/lib/web/application.py", line 420, in _delegate
E 2015-05-13 07:51:51.353
    return handle_class(cls)
E 2015-05-13 07:51:51.353
  File "/base/data/home/apps/s~kanikanikindle/1.384273015607921030/lib/web/application.py", line 396, in handle_class
E 2015-05-13 07:51:51.353
    return tocall(*args)
E 2015-05-13 07:51:51.353
  File "/base/data/home/apps/s~kanikanikindle/1.384273015607921030/apps/View/Deliver.py", line 56, in GET
E 2015-05-13 07:51:51.353
    self.queueit(user, book.key().id(), book.separate)
E 2015-05-13 07:51:51.353
  File "/base/data/home/apps/s~kanikanikindle/1.384273015607921030/apps/View/Deliver.py", line 31, in queueit
E 2015-05-13 07:51:51.353
    params=param,target="worker")
E 2015-05-13 07:51:51.353
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/taskqueue/taskqueue.py", line 2286, in add
E 2015-05-13 07:51:51.353
    queue_name=queue_name, transactional=transactional)
E 2015-05-13 07:51:51.353
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/taskqueue/taskqueue.py", line 1134, in add
E 2015-05-13 07:51:51.353
    return self.add_async(queue_name, transactional).get_result()
E 2015-05-13 07:51:51.353
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/apiproxy_stub_map.py", line 613, in get_result
E 2015-05-13 07:51:51.353
    return self.__get_result_hook(self)
E 2015-05-13 07:51:51.353
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/taskqueue/taskqueue.py", line 1960, in ResultHook
E 2015-05-13 07:51:51.353
    raise exception
E 2015-05-13 07:51:51.353
UnknownQueueError
```

**Comment by cdhigh** [comment]
请参考历史答复
