### ISSUE TITLE
Deliver now issue

### ISSUE THREAD

**Issue by ouwenxxing** [cdhigh/KindleEar#200]
订阅后
再按Deliver Now会出现 internal server error

以下是stacktrace
2015-05-29 17:35:15.467 /deliver?u=ouwenxxing 500 244ms 0kb Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.81 Safari/537.36 module=default version=1
E 2015-05-29 17:35:15.458 Traceback (most recent call last):
E 2015-05-29 17:35:15.459 File "/base/data/home/apps/s~ouwenkindle/1.384643866630437072/lib/web/application.py", line 239, in process
E 2015-05-29 17:35:15.459 return self.handle()
E 2015-05-29 17:35:15.459 File "/base/data/home/apps/s~ouwenkindle/1.384643866630437072/lib/web/application.py", line 230, in handle
E 2015-05-29 17:35:15.459 return self._delegate(fn, self.fvars, args)
E 2015-05-29 17:35:15.459 File "/base/data/home/apps/s~ouwenkindle/1.384643866630437072/lib/web/application.py", line 420, in _delegate
E 2015-05-29 17:35:15.459 return handle_class(cls)
E 2015-05-29 17:35:15.459 File "/base/data/home/apps/s~ouwenkindle/1.384643866630437072/lib/web/application.py", line 396, in handle_class
E 2015-05-29 17:35:15.459 return tocall(*args)
E 2015-05-29 17:35:15.459 File "/base/data/home/apps/s~ouwenkindle/1.384643866630437072/apps/View/Deliver.py", line 56, in GET
E 2015-05-29 17:35:15.459 self.queueit(user, book.key().id(), book.separate)
E 2015-05-29 17:35:15.459 File "/base/data/home/apps/s~ouwenkindle/1.384643866630437072/apps/View/Deliver.py", line 31, in queueit
E 2015-05-29 17:35:15.459 params=param,target="worker")
E 2015-05-29 17:35:15.459 File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/taskqueue/taskqueue.py", line 2286, in add
E 2015-05-29 17:35:15.459 queue_name=queue_name, transactional=transactional)
E 2015-05-29 17:35:15.459 File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/taskqueue/taskqueue.py", line 1134, in add
E 2015-05-29 17:35:15.459 return self.add_async(queue_name, transactional).get_result()
E 2015-05-29 17:35:15.459 File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/apiproxy_stub_map.py", line 613, in get_result
E 2015-05-29 17:35:15.459 return self.__get_result_hook(self)
E 2015-05-29 17:35:15.460 File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/taskqueue/taskqueue.py", line 1960, in ResultHook
E 2015-05-29 17:35:15.460 raise exception
E 2015-05-29 17:35:15.460 UnknownQueueError

也不知道为什么会出现这个原因？

**Comment by ouwenxxing** [comment]
好像GAE版本升级了，默认不会上传cron , queues , dispatch ，执行以下命令手动更新

python appcfg.py update_cron KindleEar/ 
python appcfg.py update_queues KindleEar-master/ 
python appcfg.py update_dispatch KindleEar-master/
