### ISSUE TITLE
请问cdhigh大神我怎么就部署不上去，报错694 ERROR appcfg.py:2449 An error occurred processing file ' ': [Errno 10060] . Aborting.

### ISSUE THREAD

**Issue by meiyujack** [cdhigh/KindleEar#208]
cdhigh您好！我不管是用cmd模式还是GAE launcher都是那个错，我的两个yaml和config文件都按照你的要求改了的。OS:Win 7 64bit Python:2.7.10 GAE SDK:1.9.22 真心搞不懂，试了很多次了，望指教。
详细输出界面如下：
c:\Program Files (x86)\Google\google_appengine>c:\python27\python.exe
appcfg.py update c:\users\my\applications\mywhitekindleear\app.yaml c:\users\my\applicatio
ns\mywhitekindleear\module-worker.yaml
05:15 PM Host: appengine.google.com
05:15 PM Application: mywhitekindleear; version: 1
05:15 PM
Starting update of app: mywhitekindleear, version: 1
05:15 PM Getting current resource limits.
2015-06-19 17:23:38,694 ERROR appcfg.py:2449 An error occurred processing file '
': [Errno 10060] . Aborting.
Traceback (most recent call last):
  File "appcfg.py", line 133, in <module>
    run_file(__file__, globals())
  File "appcfg.py", line 129, in run_file
    execfile(_PATHS.script_file(script_name), globals_)
  File "c:\Program Files (x86)\Google\google_appengine\google\appengine\tools\ap
pcfg.py", line 5486, in <module>
    main(sys.argv)
  File "c:\Program Files (x86)\Google\google_appengine\google\appengine\tools\ap
pcfg.py", line 5477, in main
    result = AppCfgApp(argv).Run()
  File "c:\Program Files (x86)\Google\google_appengine\google\appengine\tools\ap
pcfg.py", line 3018, in Run
    self.action(self)
  File "c:\Program Files (x86)\Google\google_appengine\google\appengine\tools\ap
pcfg.py", line 5133, in __call__
    return method()
  File "c:\Program Files (x86)\Google\google_appengine\google\appengine\tools\ap
pcfg.py", line 3825, in Update
    self.UpdateUsingSpecificFiles()
  File "c:\Program Files (x86)\Google\google_appengine\google\appengine\tools\ap
pcfg.py", line 3817, in UpdateUsingSpecificFiles
    self.UpdateVersion(rpcserver, self.basepath, module_yaml, file_name)
  File "c:\Program Files (x86)\Google\google_appengine\google\appengine\tools\ap
pcfg.py", line 3793, in UpdateVersion
    return appversion.DoUpload(paths, openfunc)
  File "c:\Program Files (x86)\Google\google_appengine\google\appengine\tools\ap
pcfg.py", line 2439, in DoUpload
    self.error_fh)
  File "c:\Program Files (x86)\Google\google_appengine\google\appengine\tools\ap
pcfg.py", line 493, in GetResourceLimits
    resource_limits.update(_GetRemoteResourceLimits(logging_context))
  File "c:\Program Files (x86)\Google\google_appengine\google\appengine\tools\ap
pcfg.py", line 463, in _GetRemoteResourceLimits
    yaml_data = logging_context.Send('/api/appversion/getresourcelimits')
  File "c:\Program Files (x86)\Google\google_appengine\google\appengine\tools\ap
pcfg.py", line 1749, in Send
    result = self.rpcserver.Send(url, payload=payload, **kwargs)
  File "c:\Program Files (x86)\Google\google_appengine\google\appengine\tools\ap
pengine_rpc_httplib2.py", line 236, in Send
    url, method=method, body=payload, headers=headers)
  File "c:\Program Files (x86)\Google\google_appengine\lib\httplib2\httplib2\__i
nit__.py", line 1584, in request
    (response, content) = self._request(conn, authority, uri, request_uri, metho
d, body, headers, redirections, cachekey)
  File "c:\Program Files (x86)\Google\google_appengine\lib\httplib2\httplib2\__i
nit__.py", line 1332, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, he
aders)
  File "c:\Program Files (x86)\Google\google_appengine\lib\httplib2\httplib2\__i
nit__.py", line 1306, in _conn_request
    conn.connect()
  File "c:\Program Files (x86)\Google\google_appengine\lib\httplib2\httplib2\__i
nit__.py", line 1053, in connect
    raise socket.error, msg
socket.error: [Errno 10060]

c:\Program Files (x86)\Google\google_appengine>

**Comment by cdhigh** [comment]
墙吧
如果不会部署，建议使用uploader，使用uploader不行再求助。

**Comment by meiyujack** [comment]
Oh,Yes!这一回用了自由门成功了！以前也用了不知道为什么不行。谢谢大大！
