### ISSUE TITLE
更新1.20.21后下载OPML文件失败

### ISSUE THREAD

**Issue by ibrother** [cdhigh/KindleEar#222]
报错信息依然是经典的internal server error

**Comment by cdhigh** [comment]
gae后台的logs呢

**Comment by ibrother** [comment]
2015-08-02 18:00:29.636 /advexport 500 144ms 0kb Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.125 Safari/537.36 module=default version=1
209.141.47.164 - - [02/Aug/2015:18:00:29 -0700] "GET /advexport HTTP/1.1" 500 155 "http://feed4ikindle.appspot.com/advimport" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.125 Safari/537.36" "feed4ikindle.appspot.com" ms=145 cpu_ms=142 cpm_usd=0.000017 app_engine_release=1.9.24 instance=00c61b117cad47c420671d9e8663abe5268f94fa
E 2015-08-02 18:00:29.632
Traceback (most recent call last):
E 2015-08-02 18:00:29.632
  File "/base/data/home/apps/s~feed4ikindle/1.385936459746565898/lib/web/application.py", line 239, in process
E 2015-08-02 18:00:29.632
    return self.handle()
E 2015-08-02 18:00:29.632
  File "/base/data/home/apps/s~feed4ikindle/1.385936459746565898/lib/web/application.py", line 230, in handle
E 2015-08-02 18:00:29.632
    return self._delegate(fn, self.fvars, args)
E 2015-08-02 18:00:29.632
  File "/base/data/home/apps/s~feed4ikindle/1.385936459746565898/lib/web/application.py", line 420, in _delegate
E 2015-08-02 18:00:29.632
    return handle_class(cls)
E 2015-08-02 18:00:29.632
  File "/base/data/home/apps/s~feed4ikindle/1.385936459746565898/lib/web/application.py", line 396, in handle_class
E 2015-08-02 18:00:29.632
    return tocall(*args)
E 2015-08-02 18:00:29.632
  File "/base/data/home/apps/s~feed4ikindle/1.385936459746565898/apps/View/Adv.py", line 224, in GET
E 2015-08-02 18:00:29.632
    (feed.title, urllib.quote_plus(feed.url), feed.isfulltext))
E 2015-08-02 18:00:29.632
  File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/urllib.py", line 1270, in quote_plus
E 2015-08-02 18:00:29.632
    return quote(s, safe)
E 2015-08-02 18:00:29.632
  File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/urllib.py", line 1263, in quote
E 2015-08-02 18:00:29.632
    return ''.join(map(quoter, s))
E 2015-08-02 18:00:29.632
KeyError: u'\u6781'

**Comment by cdhigh** [comment]
url中有中文吧
现在还不支持URL中有中文，我看看如何修改以便支持。

**Comment by ibrother** [comment]
url指的是自定义rss源的吗？

**Comment by cdhigh** [comment]
是的，python的一个库函数不支持包含unicode的URL导致此问题。
这也是python2社区最头疼的字符编码问题，时不时就要踩一次雷。
如果GAE支持python3就会好很多。
升级1.20.22就好了，导出后会将unicode字符编码为utf-8导出。
不过如果你需要重新导入，我也不打算将导入后的字符恢复为正常的汉字显示，还是保持utf-8编码，反正最后浏览器发出的请求都是要转换为utf-8编码的。

**Comment by ibrother** [comment]
可以的啊,反正不阅读url, 谢谢作者解决问题!!
