### ISSUE TITLE
如何才能更新自己的kindleear版本？

### ISSUE THREAD

**Issue by samlinee** [cdhigh/KindleEar#284]
我自己的http://xxx.appspot.com 下方显示的是2013 © KindleEar @1.20.23

**Comment by cdhigh** [comment]
下载新版本重新上传即可

**Comment by samlinee** [comment]
我尝试了一下 发现如下结果：
请问这是什么情况 ？是代理的问题吗？我用的是shadowsocks 全局模式。
帮忙我解决一下 非常感谢！

Your custom info :
          app id : samlin-kindle
           email : linsheng.ee@gmail.com
        timezone : 8
Correct? (y/n) : y

C:\Users\SamLIN\Desktop\kindleear>if errorlevel 1 pause && exit

C:\Users\SamLIN\Desktop\kindleear>if exist KindleEar goto kindle

C:\Users\SamLIN\Desktop\kindleear>python.exe appcfg.py --skip_sdk_update_check update KindleEar\app.yaml KindleEar\module-worker.yaml
07:34 PM Host: appengine.google.com
07:34 PM Application: samlin-kindle; version: 1
07:34 PM
Starting update of app: samlin-kindle, version: 1
07:34 PM Getting current resource limits.
Email: linsheng.ee@gmail.com
Password for linsheng.ee@gmail.com:
07:34 PM Scanning files on local disk.
07:34 PM Cloning 15 static files.
07:35 PM Cloning 387 application files.
07:35 PM Compilation starting.
07:35 PM Compilation completed.
07:35 PM Starting deployment.
07:35 PM Checking if deployment succeeded.
07:35 PM Deployment successful.
07:35 PM Checking if updated app version is serving.
07:36 PM Completed update of app: samlin-kindle, version: 1
07:36 PM Application: samlin-kindle; module: worker; version: 1
07:36 PM
Starting update of app: samlin-kindle, module: worker, version: 1
07:36 PM Getting current resource limits.
07:36 PM Scanning files on local disk.
07:36 PM Cloning 15 static files.
2016-04-04 19:36:19,526 ERROR appcfg.py:2487 An unexpected error occurred. Aborting.
Traceback (most recent call last):
  File "C:\Users\SamLIN\Desktop\kindleear\google\appengine\tools\appcfg.py", line 2327, in DoUpload
    missing_files = self.Begin()
  File "C:\Users\SamLIN\Desktop\kindleear\google\appengine\tools\appcfg.py", line 1963, in Begin
    CloneFiles('/api/appversion/cloneblobs', blobs_to_clone, 'static')
  File "C:\Users\SamLIN\Desktop\kindleear\google\appengine\tools\appcfg.py", line 1952, in CloneFiles
    payload=BuildClonePostBody(chunk))
  File "C:\Users\SamLIN\Desktop\kindleear\google\appengine\tools\appcfg.py", line 1683, in Send
    result = self.rpcserver.Send(url, payload=payload, **kwargs)
  File "C:\Users\SamLIN\Desktop\kindleear\google\appengine\tools\appengine_rpc.py", line 409, in Send
    f = self.opener.open(req)
  File "C:\Users\SamLIN\Desktop\kindleear\lib\urllib2.py", line 404, in open
    response = self._open(req, data)
  File "C:\Users\SamLIN\Desktop\kindleear\lib\urllib2.py", line 422, in _open
    '_open', req)
  File "C:\Users\SamLIN\Desktop\kindleear\lib\urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "C:\Users\SamLIN\Desktop\kindleear\lib\urllib2.py", line 1222, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "C:\Users\SamLIN\Desktop\kindleear\lib\fancy_urllib\fancy_urllib\__init__.py", line 387, in do_open
    raise url_error
URLError: <urlopen error [Errno 8] _ssl.c:504: EOF occurred in violation of protocol>
07:36 PM Rolling back the update.
Traceback (most recent call last):
  File "appcfg.py", line 170, in <module>
    run_file(__file__, globals())
  File "appcfg.py", line 166, in run_file
    execfile(script_path, globals_)
  File "C:\Users\SamLIN\Desktop\kindleear\google\appengine\tools\appcfg.py", line 5214, in <module>
    main(sys.argv)
  File "C:\Users\SamLIN\Desktop\kindleear\google\appengine\tools\appcfg.py", line 5205, in main
    result = AppCfgApp(argv).Run()
  File "C:\Users\SamLIN\Desktop\kindleear\google\appengine\tools\appcfg.py", line 2885, in Run
    self.action(self)
  File "C:\Users\SamLIN\Desktop\kindleear\google\appengine\tools\appcfg.py", line 4884, in __call__
    return method()
  File "C:\Users\SamLIN\Desktop\kindleear\google\appengine\tools\appcfg.py", line 3649, in Update
    self.UpdateUsingSpecificFiles()
  File "C:\Users\SamLIN\Desktop\kindleear\google\appengine\tools\appcfg.py", line 3641, in UpdateUsingSpecificFiles
    self.UpdateVersion(rpcserver, self.basepath, module_yaml, file_name)
  File "C:\Users\SamLIN\Desktop\kindleear\google\appengine\tools\appcfg.py", line 3617, in UpdateVersion
    return appversion.DoUpload(paths, openfunc)
  File "C:\Users\SamLIN\Desktop\kindleear\google\appengine\tools\appcfg.py", line 2327, in DoUpload
    missing_files = self.Begin()
  File "C:\Users\SamLIN\Desktop\kindleear\google\appengine\tools\appcfg.py", line 1963, in Begin
    CloneFiles('/api/appversion/cloneblobs', blobs_to_clone, 'static')
  File "C:\Users\SamLIN\Desktop\kindleear\google\appengine\tools\appcfg.py", line 1952, in CloneFiles
    payload=BuildClonePostBody(chunk))
  File "C:\Users\SamLIN\Desktop\kindleear\google\appengine\tools\appcfg.py", line 1683, in Send
    result = self.rpcserver.Send(url, payload=payload, **kwargs)
  File "C:\Users\SamLIN\Desktop\kindleear\google\appengine\tools\appengine_rpc.py", line 409, in Send
    f = self.opener.open(req)
  File "C:\Users\SamLIN\Desktop\kindleear\lib\urllib2.py", line 404, in open
    response = self._open(req, data)
  File "C:\Users\SamLIN\Desktop\kindleear\lib\urllib2.py", line 422, in _open
    '_open', req)
  File "C:\Users\SamLIN\Desktop\kindleear\lib\urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "C:\Users\SamLIN\Desktop\kindleear\lib\urllib2.py", line 1222, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "C:\Users\SamLIN\Desktop\kindleear\lib\fancy_urllib\fancy_urllib\__init__.py", line 387, in do_open
    raise url_error
urllib2.URLError: <urlopen error [Errno 8] _ssl.c:504: EOF occurred in violation of protocol>

C:\Users\SamLIN\Desktop\kindleear>python.exe appcfg.py --skip_sdk_update_check update KindleEar
07:36 PM Application: samlin-kindle; version: 1
07:36 PM Host: appengine.google.com
07:36 PM
Starting update of app: samlin-kindle, version: 1
07:36 PM Getting current resource limits.
Email:

**Comment by samlinee** [comment]
虽然不明白怎么回事 不过我的http://xxx.appspot.com/ 下已经显示2013 - 2016 © KindleEar @1.23

**Comment by cdhigh** [comment]
碰到URLLIB2的URLERROR错误一般都是梯子问题，既然你已经部署成功，但是又出现这个错误，说明文件已经上传了，只是后面的更新索引、任务设置等的子任务出错，不过因为此版本没有修过其他东西，所以应该不影响。

**Comment by samlinee** [comment]
我现在又遇到了一个问题 订阅您所提供的源的时候，例如

> 已订阅 
> 
> 华尔街日报 
> 
> 退订 
> 
> 每天最重要的商业财经要闻及金融市场综述 
> 
> 
> 知乎日報 
> 
> 退订 
> 
> 知乎日报全文RSS，不需要转发，排版图片正常。 
> 
> 
> 爱思想一周排行 
> 
> 退订 
> 
> 最具原创性和思想性的中文学术平台之一。每周六推送。 
> 
> 
> 雪球今日话题 
> 
> 退订 
> 
> 雪球是一个社交投资网络，「今日话题」是雪球用户每日发布的投资交流精选。 

却完全没有得到推送
感谢您的回答

**Comment by cdhigh** [comment]
完全没有推送就要看worker模块的logs

**Comment by samlinee** [comment]
您好  请问您方便详细一点和我说吗？

> C:\Users\SamLIN\Desktop\kindleear\KindleEar\apps\Work\worker.py

您好请问是这个worker.py下吗？应该怎么设置才好呢？

**Comment by cdhigh** [comment]
appengine.google.com, 然后打开logs界面，选择worker模块

**Comment by samlinee** [comment]
2016-04-07 07:34:23.728 fulltext feed item no has desc,link to webpage for article.(小权：预计宝莱特今年净利7500万) 



W 
2016-04-07 07:34:23.729 fulltext feed item no has desc,link to webpage for article.(我为什么买公募基金，从不买P2P) 


W 
2016-04-07 07:34:23.729 fulltext feed item no has desc,link to webpage for article.(攻略：如何快速获得经济数据) 


W 
2016-04-07 07:34:23.729 fulltext feed item no has desc,link to webpage for article.(四大利空或消除，银行股有机会？) 


W 
2016-04-07 07:34:23.729 fulltext feed item no has desc,link to webpage for article.(也谈保守投资：不要超出能力圈) 


W 
2016-04-07 07:34:23.729 fulltext feed item no has desc,link to webpage for article.(投资必修课：要想成功先避免失败) 


W 
2016-04-07 07:34:23.730 fulltext feed item no has desc,link to webpage for article.(数据说话：一季报五大行业高增长) 


W 
2016-04-07 07:34:23.730 fulltext feed item no has desc,link to webpage for article.(金禾实业：进可攻退可守的标的？) 


W 
2016-04-07 07:34:23.730 fulltext feed item no has desc,link to webpage for article.(开P2P公司高大上？真相是这样) 


W 
2016-04-07 07:34:23.730 fulltext feed item no has desc,link to webpage for article.(不玩P2P，这四种理财方式可考虑) 


W 
2016-04-07 07:34:23.730 fulltext feed item no has desc,link to webpage for article.(贝因美，好时光一去不复返？) 


W 
2016-04-07 07:34:23.730 fulltext feed item no has desc,link to webpage for article.(债转股无利好，防范泥沙俱下) 


W 
2016-04-07 07:34:23.731 fulltext feed item no has desc,link to webpage for article.(瑞贝卡：假发行业可能爆发？) 


W 
2016-04-07 07:34:23.731 fulltext feed item no has desc,link to webpage for article.(我为什么买公募基金，从不买P2P) 


W 
2016-04-07 07:34:23.731 fulltext feed item no has desc,link to webpage for article.(10000雪球币征集靠谱理财方式！) 


W 
2016-04-07 07:34:23.731 fulltext feed item no has desc,link to webpage for article.(资源类股长线投资机会来了？) 


W 
2016-04-07 07:34:23.731 fulltext feed item no has desc,link to webpage for article.(未来，什么股能领涨创业板？) 


W 
2016-04-07 07:34:23.731 fulltext feed item no has desc,link to webpage for article.(沪指跳水回踩3000点，创业板跌2%) 


W 
2016-04-07 07:34:23.732 fulltext feed item no has desc,link to webpage for article.(陌陌大涨33%，壳股又要发疯？) 


W 
2016-04-07 07:34:23.732 fulltext feed item no has desc,link to webpage for article.(P2P不能买，要买就买交易所债！) 


W 
2016-04-07 07:34:24.183 fetch page failed(403 Forbidden):http://xueqiu.com/6413254712/67127162. 


W 
2016-04-07 07:34:24.235 fetch page failed(403 Forbidden):http://xueqiu.com/8152922548/67130801. 


W 
2016-04-07 07:34:24.837 fetch page failed(403 Forbidden):http://xueqiu.com/8220406949/67122416. 


W 
2016-04-07 07:34:24.901 fetch page failed(403 Forbidden):http://xueqiu.com/1910783512/67106275. 


W 
2016-04-07 07:34:24.955 fetch page failed(403 Forbidden):http://xueqiu.com/5430985804/67117789. 


W 
2016-04-07 07:34:25.014 fetch page failed(403 Forbidden):http://xueqiu.com/9586083092/67117621. 


W 
2016-04-07 07:34:25.075 fetch page failed(403 Forbidden):http://xueqiu.com/2228854973/67115281. 


W 
2016-04-07 07:34:25.130 fetch page failed(403 Forbidden):http://xueqiu.com/6007117747/67114424. 


W 
2016-04-07 07:34:25.192 fetch page failed(403 Forbidden):http://xueqiu.com/1965298928/67104924. 


W 
2016-04-07 07:34:25.245 fetch page failed(403 Forbidden):http://xueqiu.com/6146592061/67103385. 


W 
2016-04-07 07:34:25.299 fetch page failed(403 Forbidden):http://xueqiu.com/5711199976/67111736. 


W 
2016-04-07 07:34:25.351 fetch page failed(403 Forbidden):http://xueqiu.com/9564664610/67102540. 


W 
2016-04-07 07:34:25.408 fetch page failed(403 Forbidden):http://xueqiu.com/9459618711/67084298. 


W 
2016-04-07 07:34:25.461 fetch page failed(403 Forbidden):http://xueqiu.com/1062883669/67093864. 


W 
2016-04-07 07:34:25.513 fetch page failed(403 Forbidden):http://xueqiu.com/8152922548/67091993. 


W 
2016-04-07 07:34:25.566 fetch page failed(403 Forbidden):http://xueqiu.com/7337745643/67080812. 


W 
2016-04-07 07:34:25.619 fetch page failed(403 Forbidden):http://xueqiu.com/7953251915/67075447. 


W 
2016-04-07 07:34:25.676 fetch page failed(403 Forbidden):http://xueqiu.com/8152922548/67087472. 


W 
2016-04-07 07:34:25.733 fetch page failed(403 Forbidden):http://xueqiu.com/4074947120/67079288. 


W 
2016-04-07 07:34:25.790 fetch page failed(403 Forbidden):http://xueqiu.com/6146592061/67079826. 


W 
2016-04-07 07:38:23.824 fetch rss failed(534 DownloadError):http:// http://zhihurss.miantiao.me/dailyrss 


W 
2016-04-07 07:38:23.833 fetch rss failed(534 DownloadError):http://pipes.yahoo.com/pipes/pipe.run?_id=8dc1c233d54b9713afc48e9d8d4c1cf6&_render=rss

**Comment by samlinee** [comment]
这是之前的

> W 
> 2016-04-05 07:35:24.456 fetch page failed(451):http://zhuanlan.zhihu.com/p/20571699. 
> 
> 
> W 
> 2016-04-05 07:35:24.457 fetch page failed(451):http://zhuanlan.zhihu.com/p/20529795. 
> 
> 
> W 
> 2016-04-05 07:35:24.458 fetch page failed(451):http://zhuanlan.zhihu.com/p/20277633. 
> 
> 
> W 
> 2016-04-05 07:35:24.459 fetch page failed(451):http://zhuanlan.zhihu.com/p/20255116. 
> 
> 
> W 
> 2016-04-05 07:35:24.460 fetch page failed(451):http://zhuanlan.zhihu.com/p/20202275. 
> 
> 
> W 
> 2016-04-05 07:35:24.461 fetch page failed(451):http://zhuanlan.zhihu.com/p/20067519. 
> 
> 
> W 
> 2016-04-05 07:35:24.462 fetch page failed(451):http://zhuanlan.zhihu.com/p/20036954. 
> 
> 
> W 
> 2016-04-05 07:35:24.463 fetch page failed(451):http://zhuanlan.zhihu.com/p/20001768. 
> 
> 
> W 
> 2016-04-05 07:35:24.464 fetch page failed(451):http://zhuanlan.zhihu.com/p/19996285. 
>

**Comment by cdhigh** [comment]
请自搭转发器。
https://github.com/cdhigh/Forwarder
