### ISSUE TITLE
运行appctg.py提示连接超时

### ISSUE THREAD

**Issue by starqiu** [cdhigh/KindleEar#290]
运行 `c:\python27\python.exe appcfg.py update kindleear目录\app.yaml kindleear目录\module-worker.yaml`时，等待许久之后，出现如下错误。但是我能访问my_app_id.appspot.com，请问到底是那个网址我访问不了导致超时呢？
```
2016-04-12 16:54:45,088 ERROR appcfg.py:2396 An error occurred processing file '': [Errno 110] Connection timed out. Aborting. 
Traceback (most recent call last):
  File "appcfg.py", line 133, in <module>
    run_file(__file__, globals())
  File "appcfg.py", line 129, in run_file
    execfile(_PATHS.script_file(script_name), globals_)
  File "/home/starqiu/program/google_appengine/google/appengine/tools/appcfg.py", line 5397, in <module>
    main(sys.argv)
  File "/home/starqiu/program/google_appengine/google/appengine/tools/appcfg.py", line 5388, in main
    result = AppCfgApp(argv).Run()
  File "/home/starqiu/program/google_appengine/google/appengine/tools/appcfg.py", line 2951, in Run
    self.action(self)
  File "/home/starqiu/program/google_appengine/google/appengine/tools/appcfg.py", line 5044, in __call__
    return method()
  File "/home/starqiu/program/google_appengine/google/appengine/tools/appcfg.py", line 3753, in Update
    self.UpdateUsingSpecificFiles()
  File "/home/starqiu/program/google_appengine/google/appengine/tools/appcfg.py", line 3745, in UpdateUsingSpecificFiles
    self.UpdateVersion(rpcserver, self.basepath, module_yaml, file_name)
  File "/home/starqiu/program/google_appengine/google/appengine/tools/appcfg.py", line 3721, in UpdateVersion
    return appversion.DoUpload(paths, openfunc)
  File "/home/starqiu/program/google_appengine/google/appengine/tools/appcfg.py", line 2386, in DoUpload
    self.error_fh)
  File "/home/starqiu/program/google_appengine/google/appengine/tools/appcfg.py", line 484, in GetResourceLimits
    resource_limits.update(_GetRemoteResourceLimits(logging_context))
  File "/home/starqiu/program/google_appengine/google/appengine/tools/appcfg.py", line 454, in _GetRemoteResourceLimits
    yaml_data = logging_context.Send('/api/appversion/getresourcelimits')
  File "/home/starqiu/program/google_appengine/google/appengine/tools/appcfg.py", line 1696, in Send
    result = self.rpcserver.Send(url, payload=payload, **kwargs)
  File "/home/starqiu/program/google_appengine/google/appengine/tools/appengine_rpc_httplib2.py", line 247, in Send
    url, method=method, body=payload, headers=headers)
  File "/home/starqiu/program/google_appengine/lib/httplib2/httplib2/__init__.py", line 1584, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/home/starqiu/program/google_appengine/lib/httplib2/httplib2/__init__.py", line 1332, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/home/starqiu/program/google_appengine/lib/httplib2/httplib2/__init__.py", line 1306, in _conn_request
    conn.connect()
  File "/home/starqiu/program/google_appengine/lib/httplib2/httplib2/__init__.py", line 1053, in connect
    raise socket.error, msg
socket.error: [Errno 110] Connection timed out
```

**Comment by cdhigh** [comment]
这是Gae SDK的网络连接出错，梯子不稳定吧。

**Comment by starqiu** [comment]
我是使用修改hosts的方式翻墙的，貌似地址过期了。使用以下方法解决了：
1. `ping www.google.com.hk` 得到google实时ip：`220.255.2.153`
2. hosts新增`220.255.2.153 appengine.google.com`
3. 重新运行`c:\python27\python.exe appcfg.py update kindleear目录\app.yaml kindleear目录\module-worker.yaml`

如果hosts中已经存在appengine.google.com直接修改相应的ip
