### ISSUE TITLE
上传成功后xxx.appspot.com显示500错误

### ISSUE THREAD

**Issue by 54wedge** [cdhigh/KindleEar#323]
Cloning 385 application files，感觉问题在这一行，别人的值是387。google could platform上显示的错误报告：
ImportError: No module named lib.memcachestore
at <module> (/base/data/home/apps/s~wedge0909/1.393759450190386619/apps/module_front.py:44)
at LoadObject (/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py:96)
at _LoadHandler (/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py:299)
at Handle (/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py:240)
新手，希望有用。

**Comment by wedgeblack** [comment]
log:
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 96, in LoadObject
    __import__(cumulative_path)
  File "/base/data/home/apps/s~wedge0909/1.393759450190386619/apps/module_front.py", line 44, in <module>
    from lib.memcachestore import MemcacheStore
ImportError: No module named lib.memcachestore

**Comment by miaowm5** [comment]
尝试重新上传
或者检查一下你上传的 KE，lib 目录下是否有 memcachestore.py 这个文件

**Comment by wedgeblack** [comment]
这个文件是有的。再次上传会有一样的问题。 @miaowm5
