### ISSUE TITLE
TypeError: do_open() got an unexpected keyword argument 'context'  Error

### ISSUE THREAD

**Issue by DamonOre** [cdhigh/KindleEar#340]
C:\Program Files (x86)\Google\google_appengine>c:\python27\python.exe appcfg.py update c:\kindleear\app.yaml c:\kindleear\module-worker.yaml

08:45 PM Host: appengine.google.com
08:45 PM Application: dadadadadamonorekindleear; version: 1
08:45 PM
Starting update of app: dadadadadamonorekindleear, version: 1
08:45 PM Getting current resource limits.
Traceback (most recent call last):
  File "appcfg.py", line 126, in <module>
    run_file(**file**, globals())
  File "appcfg.py", line 122, in run_file
    execfile(_PATHS.script_file(script_name), globals_)
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py", line 5400, in <module>
    main(sys.argv)
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py", line 5391, in main
    result = AppCfgApp(argv).Run()
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py", line 2981, in Run
    self.action(self)
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py", line 5047, in **call**
    return method()
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py", line 3764, in Update
    self.UpdateUsingSpecificFiles()
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py", line 3756, in UpdateUsingSpecificFiles
    self.UpdateVersion(rpcserver, self.basepath, module_yaml, file_name)
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py", line 3732, in UpdateVersion
    return appversion.DoUpload(paths, openfunc)
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py", line 2406, in DoUpload
    self.error_fh)
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py", line 484, in GetResourceLimits
    resource_limits.update(_GetRemoteResourceLimits(logging_context))
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py", line 454, in _GetRemoteResourceLimits
    yaml_data = logging_context.Send('/api/appversion/getresourcelimits')
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py", line 1740, in Send
    result = self.rpcserver.Send(url, payload=payload, *_kwargs)
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appengine_rpc.py", line 405, in Send
    f = self.opener.open(req)
  File "c:\python27\lib\urllib2.py", line 429, in open
    response = self._open(req, data)
  File "c:\python27\lib\urllib2.py", line 447, in _open
    '_open', req)
  File "c:\python27\lib\urllib2.py", line 407, in _call_chain
    result = func(_args)
  File "c:\python27\lib\urllib2.py", line 1241, in https_open
    context=self._context)
TypeError: do_open() got an unexpected keyword argument 'context'

upload log,Win10 x64

**Comment by DamonOre** [comment]
GoogleAppEngine 换成 1.9.40 就不在出现这个问题。
