### ISSUE TITLE
一些自定义rss需要翻墙才能访问，Q&A给出升级版本所以我想问怎么升级

### ISSUE THREAD

**Issue by ZJJane** [cdhigh/KindleEar#447]
当前的版本怎么查看，又怎么升级

**Comment by cdhigh** [comment]
应用的主页下面就有版本号显示, 重新再github上下载最新代码，再次部署就是升级版本了

**Comment by ZJJane** [comment]
标准部署中出现了问题，麻烦帮我看下，
Traceback (most recent call last):
  File "appcfg.py", line 133, in <module>
    run_file(__file__, globals())
  File "appcfg.py", line 129, in run_file
    execfile(_PATHS.script_file(script_name), globals_)
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py", line 5497, in <module>
    main(sys.argv)
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py", line 5488, in main
    result = AppCfgApp(argv).Run()
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py", line 2966, in Run
    self.action(self)
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py", line 5144, in __call__
    return method()
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py", line 3846, in Update
    self.UpdateUsingSpecificFiles()
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py", line 3838, in UpdateUsingSpecificFiles
    self.UpdateVersion(rpcserver, self.basepath, module_yaml, file_name)
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py", line 3814, in UpdateVersion
    return appversion.DoUpload(paths, openfunc)
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py", line 2401, in DoUpload
    self.error_fh)
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py", line 497, in GetResourceLimits
    resource_limits.update(_GetRemoteResourceLimits(logging_context))
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py", line 467, in _GetRemoteResourceLimits
    yaml_data = logging_context.Send('/api/appversion/getresourcelimits')
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py", line 1709, in Send
    result = self.rpcserver.Send(url, payload=payload, **kwargs)
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appengine_rpc_httplib2.py", line 246, in Send
    url, method=method, body=payload, headers=headers)
  File "C:\Program Files (x86)\Google\google_appengine\lib\oauth2client\oauth2client\client.py", line 579, in new_request
    self._refresh(request_orig)
  File "C:\Program Files (x86)\Google\google_appengine\lib\oauth2client\oauth2client\client.py", line 787, in _refresh
    self._do_refresh_request(http_request)
  File "C:\Program Files (x86)\Google\google_appengine\lib\oauth2client\oauth2client\client.py", line 806, in _do_refresh_request
    self.token_uri, method='POST', body=body, headers=headers)
  File "C:\Program Files (x86)\Google\google_appengine\lib\httplib2\httplib2\__init__.py", line 1584, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "C:\Program Files (x86)\Google\google_appengine\lib\httplib2\httplib2\__init__.py", line 1332, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "C:\Program Files (x86)\Google\google_appengine\lib\httplib2\httplib2\__init__.py", line 1268, in _conn_request
    conn.connect()
  File "C:\Program Files (x86)\Google\google_appengine\lib\httplib2\httplib2\__init__.py", line 1011, in connect
    sock.connect((self.host, self.port))
  File "C:\Program Files (x86)\Google\google_appengine\socks.py", line 362, in connect
    raise GeneralProxyError((5,_generalerrors[5]))
socks.GeneralProxyError: (5, 'bad input')

**Comment by ZJJane** [comment]
标准部署和推荐的简易部署都出现了我暂时无法解决的问题，后来再issue中看到有位仁兄用了另外的方法部署，我尝试了下总算部署成功了，但重新部署后的版本还是1.25，但FAQ又要求更新到版本到1.5以上，是我理解错了还是什么？
附上部署方法，还算简单，
1.先fork下kindleear，按要求改下标准部署要求改的那几个文件，之后打开cloud shell。（上传时，步骤的第二步 git clone https://github.com/miaowm5/KeUploader.git 改成你fork 后的地址）
2.git clone https://github.com/shmily1866/KindleEar.git
3.cd kindleear
4.appcfg.py update ./

**Comment by cdhigh** [comment]
版本1.25 比 1.5 新
