### ISSUE TITLE
投递失败？

### ISSUE THREAD

**Issue by linux40** [cdhigh/KindleEar#450]
```
0.1.0.2 - - [29/Dec/2017:10:02:59 +0800] "GET /worker?u=admin&id=5069036098420736 HTTP/1.1" 500 135 http://xxx.appspot.com/deliver?u=admin "AppEngine-Google; (+http://code.google.com/appengine)" "worker.xxx.appspot.com" ms=396633 cpu_ms=85156 cpm_usd=0.000032322853 loading_request=0 instance=00c61b117ceb9ee0fe714c58d370d11da60cdd548e3c45a4b6c72676186bf240dd13dc4cb23f00fd app_engine_release=1.9.54 trace_id=f81703ae2b4709697c32c9cac9958dd6
全部展开 | 全部收起
{
 httpRequest: {…}  
 insertId: "5a45a3df000ecc26812d9d23"  
 labels: {…}  
 logName: "projects/xxx/logs/appengine.googleapis.com%2Frequest_log"  
 operation: {…}  
 protoPayload: {…}  
 receiveTimestamp: "2017-12-29T02:09:35.975156287Z"  
 resource: {…}  
 severity: "ERROR"  
 timestamp: "2017-12-29T02:02:59.335605Z"  
}
2017-12-29 10:09:35.950 香港時間
Traceback (most recent call last):
2017-12-29 10:09:35.950 香港時間
  File "lib/web/application.py", line 239, in process
2017-12-29 10:09:35.950 香港時間
    return self.handle()
2017-12-29 10:09:35.950 香港時間
  File "lib/web/application.py", line 230, in handle
2017-12-29 10:09:35.950 香港時間
    return self._delegate(fn, self.fvars, args)
2017-12-29 10:09:35.950 香港時間
  File "lib/web/application.py", line 420, in _delegate
2017-12-29 10:09:35.950 香港時間
    return handle_class(cls)
2017-12-29 10:09:35.950 香港時間
  File "lib/web/application.py", line 396, in handle_class
2017-12-29 10:09:35.950 香港時間
    return tocall(*args)
2017-12-29 10:09:35.950 香港時間
  File "/base/data/home/apps/s~xxx/worker:1.406455606566044677/apps/Work/Worker.py", line 191, in GET
2017-12-29 10:09:35.950 香港時間
    o.convert(oeb, oIO, opts, main.log)
2017-12-29 10:09:35.950 香港時間
  File "lib/calibre/ebooks/conversion/mobioutput.py", line 143, in convert
2017-12-29 10:09:35.950 香港時間
    ) if create_kf8 else None
2017-12-29 10:09:35.950 香港時間
  File "lib/calibre/ebooks/conversion/mobioutput.py", line 155, in create_kf8
2017-12-29 10:09:35.950 香港時間
    for_joint=for_joint)
2017-12-29 10:09:35.950 香港時間
  File "lib/calibre/ebooks/mobi/writer8/main.py", line 435, in create_kf8_book
2017-12-29 10:09:35.950 香港時間
    writer = KF8Writer(oeb, opts, resources)
2017-12-29 10:09:35.950 香港時間
  File "lib/calibre/ebooks/mobi/writer8/main.py", line 62, in __init__
2017-12-29 10:09:35.950 香港時間
    self.chunk_it_up()
2017-12-29 10:09:35.950 香港時間
  File "lib/calibre/ebooks/mobi/writer8/main.py", line 267, in chunk_it_up
2017-12-29 10:09:35.950 香港時間
    chunker = Chunker(self.oeb, self.data, placeholder_map)
2017-12-29 10:09:35.950 香港時間
  File "lib/calibre/ebooks/mobi/writer8/skeleton.py", line 167, in __init__
2017-12-29 10:09:35.950 香港時間
    root = self.remove_namespaces(self.data(item))
2017-12-29 10:09:35.950 香港時間
  File "lib/calibre/ebooks/mobi/writer8/skeleton.py", line 238, in remove_namespaces
2017-12-29 10:09:35.950 香港時間
    tag.attrib.iteritems()})
2017-12-29 10:09:35.950 香港時間
  File "lxml.etree.pyx", line 1395, in lxml.etree._Element.makeelement (third_party/apphosting/python/lxml/v2_3/src/lxml/lxml.etree.c:39841)
2017-12-29 10:09:35.950 香港時間
  File "apihelpers.pxi", line 156, in lxml.etree._makeElement (third_party/apphosting/python/lxml/v2_3/src/lxml/lxml.etree.c:12231)
2017-12-29 10:09:35.950 香港時間
  File "apihelpers.pxi", line 144, in lxml.etree._makeElement (third_party/apphosting/python/lxml/v2_3/src/lxml/lxml.etree.c:12106)
2017-12-29 10:09:35.950 香港時間
  File "apihelpers.pxi", line 298, in lxml.etree._initNodeAttributes (third_party/apphosting/python/lxml/v2_3/src/lxml/lxml.etree.c:13603)
2017-12-29 10:09:35.950 香港時間
  File "apihelpers.pxi", line 1554, in lxml.etree._attributeValidOrRaise (third_party/apphosting/python/lxml/v2_3/src/lxml/lxml.etree.c:24197)
2017-12-29 10:09:35.950 香港時間
ValueError: Invalid attribute name u'v:shapes'
```

**Comment by linux40** [comment]
对了，这是12月25号更新的版本。

**Comment by linux40** [comment]
1.24.2

**Comment by linux40** [comment]
原来所有问题都是我没更新，可是脚本更新不到1.25，我删了代码后重新部署了一次就成了。
