### ISSUE TITLE
RSS推送正常，但给appspotmail.com发信显示ImportError: No module named main  

### ISSUE THREAD

**Issue by jslilei** [cdhigh/KindleEar#514]
RSS推送正常，但给appspotmail.com发信显示ImportError: No module named main  

ImportError: No module named main
POST ngc1008ll.appspot.com/_ah/mail/xxx@ngc1008ll.appspotmail.com
500 Internal Server Error

错误日志具体显示如下，想请教下是什么原因？谢谢！
{
 httpRequest: {
  status:  500    
 }
 insertId:  "5b96184e0003026cb250f271"   
 labels: {
  clone_id:  "00c61b117c8fc2d9d2d4e6ccd2d9b94010c307b036a4cca9a1285667610710d8baccdb7a69"    
 }
 logName:  "projects/ngc1008ll/logs/appengine.googleapis.com%2Frequest_log"   
 operation: {
  first:  true    
  id:  "5b96184e00ff00fff5e39c83dc370001737e6e6763313030386c6c000131000100"    
  last:  true    
  producer:  "appengine.googleapis.com/request_id"    
 }
 protoPayload: {
  @type:  "type.googleapis.com/google.appengine.logging.v1.RequestLog"    
  appEngineRelease:  "1.9.64"    
  appId:  "s~ngc1008ll"    
  cost:  1.9669e-8    
  endTime:  "2018-09-10T07:07:58.196886Z"    
  finished:  true    
  first:  true    
  host:  "ngc1008ll.appspot.com"    
  httpVersion:  "HTTP/1.1"    
  instanceId:  "00c61b117c8fc2d9d2d4e6ccd2d9b94010c307b036a4cca9a1285667610710d8baccdb7a69"    
  instanceIndex:  -1    
  ip:  "0.1.0.20"    
  latency:  "0.133939s"    
  line: [
   0: {
    logMessage:  "No module named main
Traceback (most recent call last):
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/573c2cae20d3e94a/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1511, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/573c2cae20d3e94a/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1505, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/573c2cae20d3e94a/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/573c2cae20d3e94a/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1077, in __call__
    return handler.dispatch()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/573c2cae20d3e94a/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/573c2cae20d3e94a/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/573c2cae20d3e94a/python27/python27_lib/versions/1/google/appengine/ext/webapp/mail_handlers.py", line 70, in post
    self.receive(mail.InboundEmailMessage(self.request.body))
  File "/base/data/home/apps/s~ngc1008ll/1.412467541805695536/apps/handlemail.py", line 236, in receive
    from main import local_time
ImportError: No module named main"      
    severity:  "ERROR"      
    time:  "2018-09-10T07:07:58.194910Z"      

}
  ]
  megaCycles:  "2577"    
  method:  "POST"    
  requestId:  "5b96184e00ff00fff5e39c83dc370001737e6e6763313030386c6c000131000100"    
  resource:  "/_ah/mail/xxx@ngc1008ll.appspotmail.com"    
  responseSize:  "176"    
  startTime:  "2018-09-10T07:07:58.062947Z"    
  status:  500    
  traceId:  "65b111e57c675f9e7a8a26d81e922600"    
  traceSampled:  true    
  urlMapEntry:  "apps.handlemail.appmail"    
  versionId:  "1"    
 }
 receiveTimestamp:  "2018-09-10T07:07:58.204395972Z"   
 resource: {
  labels: {
   module_id:  "default"     
   project_id:  "ngc1008ll"     
   version_id:  "1"     
   zone:  "us6"     
  }
  type:  "gae_app"    
 }
 severity:  "ERROR"   
 timestamp:  "2018-09-10T07:07:58.062947Z"   
 trace:  "projects/ngc1008ll/traces/65b111e57c675f9e7a8a26d81e922600"   
 traceSampled:  true   

E  POST 500 176 B 133 ms Unknown /_ah/mail/xxx@ngc1008ll.appspotmail.com POST 500 176 B 133 ms Unknown 5b96184e00ff00fff5e39c83dc370001737e6e6763313030386c6c000131000100
  0.1.0.20 - - [10/Sep/2018:15:07:58 +0800] "POST /_ah/mail/xxx@ngc1008ll.appspotmail.com HTTP/1.1" 500 176 - "-" "ngc1008ll.appspot.com" ms=NaN cpu_ms=2577 cpm_usd=1.9669e-8 loading_request=0 instance=00c61b117c8fc2d9d2d4e6ccd2d9b94010c307b036a4cca9a1285667610710d8baccdb7a69 app_engine_release=1.9.64 trace_id=65b111e57c675f9e7a8a26d81e922600

**Comment by cdhigh** [comment]
你找到了一个BUG，很快修正。

**Comment by cdhigh** [comment]
已修正
