### ISSUE TITLE
Errorno 10060 A connection attempt failed because the connected party did not properly respond after a period of time

### ISSUE THREAD

**Issue by gukejing** [cdhigh/KindleEar#611]
用upload.bat上传出现如下错误，已经全局翻了。

2020-05-04 16:37:00,638 ERROR appcfg.py:2323 An error occurred processing file '': <urlopen error [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>. Aborting.
Traceback (most recent call last):
  File "appcfg.py", line 170, in <module>
    run_file(__file__, globals())
  File "appcfg.py", line 166, in run_file
    execfile(script_path, globals_)
  File "C:\Users\XXX\Desktop\01-tmp\01-Download\Kindle\google\appengine\tools\appcfg.py", line 5214, in <module>
    main(sys.argv)
  File "C:\Users\XXX\Desktop\01-tmp\01-Download\Kindle\google\appengine\tools\appcfg.py", line 5205, in main
    result = AppCfgApp(argv).Run()
  File "C:\Users\XXX\Desktop\01-tmp\01-Download\Kindle\google\appengine\tools\appcfg.py", line 2885, in Run
    self.action(self)
  File "C:\Users\XXX\Desktop\01-tmp\01-Download\Kindle\google\appengine\tools\appcfg.py", line 4884, in __call__
    return method()
  File "C:\Users\XXX\Desktop\01-tmp\01-Download\Kindle\google\appengine\tools\appcfg.py", line 3649, in Update
    self.UpdateUsingSpecificFiles()
  File "C:\Users\XXX\Desktop\01-tmp\01-Download\Kindle\google\appengine\tools\appcfg.py", line 3641, in UpdateUsingSpecificFiles
    self.UpdateVersion(rpcserver, self.basepath, module_yaml, file_name)
  File "C:\Users\XXX\Desktop\01-tmp\01-Download\Kindle\google\appengine\tools\appcfg.py", line 3617, in UpdateVersion
    return appversion.DoUpload(paths, openfunc)
  File "C:\Users\XXX\Desktop\01-tmp\01-Download\Kindle\google\appengine\tools\appcfg.py", line 2313, in DoUpload
    self.error_fh)
  File "C:\Users\XXX\Desktop\01-tmp\01-Download\Kindle\google\appengine\tools\appcfg.py", line 466, in GetResourceLimits
    resource_limits.update(_GetRemoteResourceLimits(logging_context))
  File "C:\Users\XXX\Desktop\01-tmp\01-Download\Kindle\google\appengine\tools\appcfg.py", line 436, in _GetRemoteResourceLimits
    yaml_data = logging_context.Send('/api/appversion/getresourcelimits')
  File "C:\Users\XXX\Desktop\01-tmp\01-Download\Kindle\google\appengine\tools\appcfg.py", line 1683, in Send
    result = self.rpcserver.Send(url, payload=payload, **kwargs)
  File "C:\Users\XXX\Desktop\01-tmp\01-Download\Kindle\google\appengine\tools\appengine_rpc.py", line 409, in Send
    f = self.opener.open(req)
  File "C:\Users\XXX\Desktop\01-tmp\01-Download\Kindle\lib\urllib2.py", line 404, in open
    response = self._open(req, data)
  File "C:\Users\XXX\Desktop\01-tmp\01-Download\Kindle\lib\urllib2.py", line 422, in _open
    '_open', req)
  File "C:\Users\XXX\Desktop\01-tmp\01-Download\Kindle\lib\urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "C:\Users\XXX\Desktop\01-tmp\01-Download\Kindle\lib\urllib2.py", line 1222, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "C:\Users\XXX\Desktop\01-tmp\01-Download\Kindle\lib\fancy_urllib\fancy_urllib\__init__.py", line 387, in do_open
    raise url_error
urllib2.URLError: <urlopen error [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>

**Comment by cdhigh** [comment]
现在已经不支持appcfg部署，要使用gcloud部署

**Comment by gukejing** [comment]
> 现在已经不支持appcfg部署，要使用gcloud部署

谢谢作者亲自来回复
那应该怎么修复？完全的python 小白，只懂一点bash 命令而已

**Comment by cdhigh** [comment]
Readme不是有gcloud的部署方法吗

**Comment by gukejing** [comment]
> Readme不是有gcloud的部署方法吗

找到了，我的目的是建一个py 文件，抓微信公众号里面的文章，推到kindle ，参考的是FAQ 的文章，通过远程的命令行建立py 文件，然后重新布署，为了验证，布置前把books 目录等预置的小说，杂志等py 文件都先删除，但重新布置后好像预置的内容都在，微信公众号的文章也没有抓到

我看你以前有评论过微信系统封闭，不好抓。不甘心，因为有20到30个公众号，每天手动发送到kindle 太花时间了，而且如果能自动化就不用订阅那么多了
