### ISSUE TITLE
更新3.0.5docker报错

### ISSUE THREAD

**Issue by appleftg** [cdhigh/KindleEar#683]
您好，vps，docker更新3.0.5后报以下错误，帮看下，谢谢。

1.docker log错误

File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/kindleear/main.py", line 47, in <module>
    app = init_app(__name__, cfgMap, set_env, debug=False)
  File "/usr/kindleear/application/__init__.py", line 37, in init_app
    init_task_queue_service(app)
  File "/usr/kindleear/application/back_end/task_queue_apscheduler.py", line 37, in init_task_queue_service
    scheduler.start()
  File "/usr/local/lib/python3.9/site-packages/flask_apscheduler/scheduler.py", line 103, in start
    self._scheduler.start(paused=paused)
  File "/usr/local/lib/python3.9/site-packages/apscheduler/schedulers/background.py", line 35, in start
    BaseScheduler.start(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/apscheduler/schedulers/base.py", line 177, in start
    self._real_add_job(job, jobstore_alias, replace_existing)
  File "/usr/local/lib/python3.9/site-packages/apscheduler/schedulers/base.py", line 895, in _real_add_job
    self._logger.info('Added job "%s" to job store "%s"', job.name, jobstore_alias)
Message: 'Added job "%s" to job store "%s"'
Arguments: ('remove_logs', 'default')
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/logging/handlers.py", line 73, in emit
    if self.shouldRollover(record):
  File "/usr/local/lib/python3.9/logging/handlers.py", line 194, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 927, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 666, in format
    s = self.formatMessage(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 635, in formatMessage
    return self._style.format(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 434, in format
    return self._format(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 430, in _format
    return self._fmt % record.__dict__
ValueError: unsupported format character '[' (0x5b) at index 1
Call stack:
  File "/usr/local/bin/gunicorn", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]", prog=prog).run()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/base.py", line 236, in run
    super().run()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 202, in run
    self.manage_workers()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 571, in manage_workers
    self.spawn_workers()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 642, in spawn_workers
    self.spawn_worker()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/gthread.py", line 95, in init_process
    super().init_process()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/kindleear/main.py", line 47, in <module>
    app = init_app(__name__, cfgMap, set_env, debug=False)
  File "/usr/kindleear/application/__init__.py", line 37, in init_app
    init_task_queue_service(app)
  File "/usr/kindleear/application/back_end/task_queue_apscheduler.py", line 37, in init_task_queue_service
    scheduler.start()
  File "/usr/local/lib/python3.9/site-packages/flask_apscheduler/scheduler.py", line 103, in start
    self._scheduler.start(paused=paused)
  File "/usr/local/lib/python3.9/site-packages/apscheduler/schedulers/background.py", line 35, in start
    BaseScheduler.start(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/apscheduler/schedulers/base.py", line 181, in start
    self._logger.info('Scheduler started')
Message: 'Scheduler started'
Arguments: ()

2.\KindleEar\application\templates\setting.html文件格式未用“UTF-8编码”格式，网页设置页面报错。

**Comment by cdhigh** [comment]
1. 确实是gunicorn.conf.py里面有错误，但是不知为何我测试是正常的，我都用了几天了，不过现在不想去深究为何我的环境是正常的，反正肯定是错的，直接改过来就好。
2. setting.html是utf-8格式的，不知你为何说不是？

已更新3.0.6，请重新拉取。

**Comment by appleftg** [comment]
> 1. 确实是gunicorn.conf.py里面有错误，但是不知为何我测试是正常的，我都用了几天了，不过现在不想去深究为何我的环境是正常的，反正肯定是错的，直接改过来就好。
> 2. setting.html是utf-8格式的，不知你为何说不是？
> 
> 已更新3.0.6，请重新拉取。

setting.html可能是我这的问题。已重新拉取部署正常了，还是有以前的警告，不过不影响，反正也不看，谢谢。
/usr/local/lib/python3.9/site-packages/tzlocal/unix.py:193: UserWarning: Can not find any timezone configuration, defaulting to UTC.
  warnings.warn("Can not find any timezone configuration, defaulting to UTC.")

**Comment by cdhigh** [comment]
这个时区警告和KindleEar无关，
如果要消除警告，你需要设置你的VPS操作系统使用的时区，不同的系统设置方法不同，搜索一下即可。

**Comment by appleftg** [comment]
好的，在docker-compose.yml增加以下内容，没有报错了，谢谢。

docker-compose.yml
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

**Comment by cdhigh** [comment]
谢谢你的解决方案

**Comment by appleftg** [comment]
> 谢谢你的解决方案

谢谢你才对，开发出来方便大家
