### ISSUE TITLE
有一些rss总是显示nonews无法推送

### ISSUE THREAD

**Issue by jcrdxl** [cdhigh/KindleEar#700]
![image](https://github.com/user-attachments/assets/91e620e8-6ee5-421d-926a-83c0e90b1f55)
这是那个rss[https://www.52pojie.cn/forum.php?mod=rss](https://www.52pojie.cn/forum.php?mod=rss)
这是我的设置
![image](https://github.com/user-attachments/assets/e2b7625e-3f1b-40f7-93cf-4c50f6a448e0)
![image](https://github.com/user-attachments/assets/68ca82b8-e8e9-4dda-9519-537885c3e15f)
**本人小白，如能得到解答万分感谢**
如有需要看的别的东西告诉我

**Comment by jcrdxl** [comment]
![image](https://github.com/user-attachments/assets/e12189d3-ecaa-42c6-a8f9-d2a00c067351)
![image](https://github.com/user-attachments/assets/08190825-6fad-48d4-9967-9e8a46ac07ca)
只有部分可以正常推送

**Comment by cdhigh** [comment]
1. 52pojie无法推送是代码中有bug，github代码库已修正，暂未同步到Docker hub（待此issue彻底解决后再同步），不过因为52pojie是论坛格式，一层楼一层楼的，算法无法自动提取正文，所以在电子书上的阅读效果会很差，最好写一个recipe，提取里面每层楼的内容然后合并，也可以合并各个分页的内容。
2. 果壳网/澎湃新闻 我推送是正常的。
3. 酷安-晨钟酱 我不知道是哪个rss地址。

**Comment by jcrdxl** [comment]
这个酷安的是rsshub里的
https://rsshub.app/coolapk/user/630380/dynamic


![Screenshot_2024-07-19-11-45-26-100_com.termux.jpg](https://github.com/user-attachments/assets/8bd9b3b6-566c-438b-bdd4-46651ae621e9)![Screenshot_2024-07-19-11-46-17-559_com.termux.jpg](https://github.com/user-attachments/assets/2ca19808-bdcb-43c7-bd09-8c0397f3877e)
上面截图的东西我复制在下面了
```
Traceback (most recent call last):                      File "/usr/kindleear/application/lib/urlopener.py", line 105, in open_remote_url                              resp = req_func(url, data=data, headers=headers, timeout=timeout, allow_redirects=True,                   File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)           File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)               File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 703, in send                         r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 700, in send                         raise ConnectionError(e, request=request)         requests.exceptions.ConnectionError: HTTPSConnectionPool(host='feedx.net', port=443): Max retries exceeded with url: /rss/thepaper.xml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa165461c40>: Failed to establish a new connection: [Errno 101] Network unreachable'))                       
[2024-07-19 03:44:53 +0000] WARNING [news.py:1959] Failed feed: 澎湃新闻: Exception Cannot fetch https://feedx.net/rss/thepaper.xml:555 [news.py:1956->...->news.py:1956->news.py:1956]                                 [2024-07-19 03:44:53 +0000] WARNING [recipe_input.py:92] Failed to execute recipe "澎湃新闻": No articles found, aborting                                         [2024-07-19 03:44:53 +0000] WARNING [plumber.py:401] Plumber: All feeds are empty, aborting.                [2024-07-19 03:44:53 +0000] WARNING [worker.py:154] There are no new feeds available: admin: [KindleEar]    root@jcrdxlvps:~/data#
```

**Comment by jcrdxl** [comment]
这能看出问题来嘛，，为啥我的还是推不了。是服务器用docker装的

**Comment by cdhigh** [comment]
我分别在我的Oracle服务器和本机上测试，酷安和澎湃新闻 都能正常推送。

555这个错误有几种可能的情况：
1. 被墙了
2. 对方服务器封锁了你的IP
3. 你的VPS的网络配置问题
